name: Acknowledge PR / Issue

on: [issues, pull_request, pull_request_target]

jobs:

  run:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Comment
        uses: wow-actions/auto-comment@v1.0.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            Hello @{{ author }} 👋
            Thank you for raising an issue.
            
            Please make sure this issue is not similar to any other previous open or closed issues. If that isn't the case, sit back and relax. All issues will be addressed within 2 days of creation ✌🏼 

          pullRequestOpened: |
            Hello @{{ author }} 👋 
            Thank you for contributing to this repository.
            
            If you have created a new file, please refer to [this discussion](https://github.com/Nimesh-Srivastava/DSA/discussions/17#discussion-3652317) for proper naming of file. 
            
            A super linter will go through the commited file on your PR. It's not perfect though, [see this](https://github.com/Nimesh-Srivastava/DSA/discussions/20#discussion-3652983).
            
            If that were to happen, wait for 2 days. Within that time the owner will manually review the changed file and merge the PR if everything is satisfactory.
