name: Automatic event handler

on:
  push:
    branches:
      - main
      - master
  
  pull_request:
    branches:
      - main
      - master
    
  issues:
    branches:
      - main
      - master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Comment
        uses: wow-actions/auto-comment@v1.0.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            👋 @{{ author }}
            Thank you for raising an issue. Please make sure this issue is not similar to any other previous open or closed issues. 
            If that isn't the case, sit back and relax. All issues will be addressed within 2 days of creation :v 

          pullRequestOpened: |
            Hello @{{ author }} 👋 
            Thank you for contributing to the repo. 
            If you have created a new file, please refer to [this discussion]() for naming conventions. 
            A super linter will go through the commited file on your PR. It checks for any compilation or runtime errors. However, it is 
            still in development and is not perfect, so it might fail the lint task. Don't worry in such a case. Wait for 2 days. Within that time 
            I will manually review the changed file and merge if it is okay.
        
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check PR code
        uses: actions/checkout@v2
        
      - name: Lint code base
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          DISABLE_ERRORS: true
          VALIDATE_ALL_CODEBASE: false
          
