name: Code super linter

on:
  pull_request_target: 
    branches: [main, master]
  
jobs:
      
  check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check PR code
        uses: actions/checkout@v2
      
  lint:
    runs-on: ubuntu-latest
    
    steps:
      - name: Lint code base
        uses: github/super-linter/slim@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BRANCH: main
          DISABLE_ERRORS: false
          VALIDATE_ALL_CODEBASE: false
          
