name: Super-linter-on-requests

on:
  push:
    
  pull_request:
    branches: [master, main]

jobs:
  build:
    name: Lint Code Base

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code base
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          FILTER_REGEX_INCLUDE: .*(.cpp|.c)
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
